### ISSUE TITLE
Yocto and Basler daA2500-60mc problem

### ISSUE THREAD

**Issue by cleridaTEK** [basler/meta-basler-imx8#1]
Hi!

I'm currently working with the evaluation board of the imx8mp SoC from NXP [(Link)](https://www.nxp.com/document/guide/getting-started-with-the-i-mx-8m-plus-evk:GS-iMX-8M-Plus-EVK).

I have built the yocto image following the instructions of the readme in this repository and I have changed the fdtfile in uboot from the default one to the "imx8mp-evk-basler.dtb".

The problem is that the camera is being detected (in dmesg and using detect_cameras.sh it shows the model and the serial number), but no device is registered when the board boots up.

If I set up the fdtfile in uboot for any of the ones using a isp, a device is registered (I don't understand why this happens) but the camera, as it does not have isp capabilities, does not work. When I launch pylon, no camera is listed.

Any help would be much appreciated.

Carlos.

**Comment by SMA2016a** [comment]
Would share with us the camera model that you are trying to use, please?

**Comment by SMA2016a** [comment]
Just for troubleshooting purpose, try this file imx8mp-evk-dual-basler.dtb .

is the camera connected to csi port 1?

**Comment by ronin80** [comment]
Hi,
I have the same problem as cleridaTEK: I have tried several "tricks" but I can't solve it.
The problem occurs with the daA2500-60mc sensor while the daA3840-30MC model works correctly.
I reported this problem to Basler Europe Support since October 2021 and I have not received any response: we are stuck with a project in which we had foreseen the use of that device (daA2500-60mc) as it is indicated as compatible with iMX8MP and we risk that our customer imposes penalties on us.
Is there a solution to make that sensor work?
Thanks in advance.

**Comment by SMA2016a** [comment]
@ronin80 : would you send me a private message with your email ID?

**Comment by cleridaTEK** [comment]
Hi,

Days ago I found that going back to Yocto Zeus and using the basler layers designed for this version solved the problem. It seems that the port of the layers from Zeus to Hardknott has not been implemented properly.

[I have used this layers](https://www.baslerweb.com/en/downloads/software-downloads/camera-enablement-package-for-nxp-s-i-mx-8m-plus-applications-processor-1-3-1-ga/)

> Just for troubleshooting purpose, try this file imx8mp-evk-dual-basler.dtb .
> 
> is the camera connected to csi port 1?

I have tried both dual and single .dtb and none of them worked.

Regards,
Carlos.

**Comment by SMA2016a** [comment]
Thanks for the update. I will also try on my board and let you know the result.

**Comment by SMA2016a** [comment]
@ronin80 :    I don't think your case is related to cleridaTEK's. 

The main different between  daA3840-30MC and  daA2500-60mc , that daA3840-30MC  supports gstreamer  natively. 
are you able to grab image with daA2500-60mc  using pylonviewer or sdk sample code. eg grab.cpp?

**Comment by ronin80** [comment]
Hi,
Also in my case, if I use the Basler layers designed for Yocto Zeus, the daA2500-60mc sensor works: I can activate the live streaming using Gstreamer (even if the video resolution is not correct).

Support for live streaming for both sensors is indicated in the Basler documentation:

gstreamer usage for daA2500-60mc and daA3840-30mc it is possible to display live video via gstreamer using:

gst-launch-1.0 -v v4l2src device = / dev / video2 ! waylandsink

**Comment by stefanklug** [comment]
Hi @ronin80 , @cleridaTEK,
I looked into the issue. Seems there is a missing dependency with the daA2500-60mc on hardknott. To workaround it you can add
`IMAGE_INSTALL_append = " basler-daa2500-60mc-imx-isp-driver "`
to your `local.conf` and rebuld/flash the image.

Best regards,
Stefan

**Comment by ronin80** [comment]
@stefanklug 
Now it works: thanks a lot for your support!

**Comment by stefanklug** [comment]
This was fixed in the layer now.
