### ISSUE TITLE
Different source directory

### ISSUE THREAD

**Issue by gorka3reta** [basler/meta-basler-imx8#4]
After cloning basler's repos I have realised that that my "sources" directory is slightly different than the README's one. While I get this:

```
.
├── base
├── meta-basler-imx8
├── meta-basler-tools
├── meta-browser
├── meta-clang
├── meta-freescale
├── meta-freescale-3rdparty
├── meta-freescale-distro
├── meta-imx
├── meta-nxp-demo-experience
├── meta-openembedded
├── meta-python2
├── meta-qt5
├── meta-timesys
├── meta-virtualization
└── poky
```

there is no meta-virtualization in the original and I dunnot have the meta-rust folder. I have followed the instructions carefully.

I'm posting this cause it may be the cause that I cannot run "pylon" successfully after building the imx-image-full.  The error of running "pylon" persists:

```
QIconvCodec::convertToUnicode: using Latin-1 for conversion, iconv_open failed
QIconvCodec::convertFromUnicode: using Latin-1 for conversion, iconv_open failed
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the[  108.521941] audit: type=1701 audit(1655714451.990:5): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=763 comm="pylonviewer" exe="/opt/pylon/bin/pylonviewer" sig=6 res=1
 Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, webgl, xcb.

Aborted
```
My host machine is Debian 11.3.
The board is imx8mminilpd4
I have 2 cameras, daa2500-60mci and daa4200-30mci

**Comment by stefanklug** [comment]
@gorka3reta I removed the listing from the readme. It was outdated and didn't help much. The pylon error says that pylon is not able to open a display to present its GUI. "could not connect to display": seems like you want to use X11 (DISPLAY is set) but there is no x11 server listening. You need to explain your setup in more detail. Do you run pylon on the device, or via SSH/remote X? Did you build with x11 support (DISTRO=fsl-imx-xwayland)?

**Comment by gorka3reta** [comment]
Hi @stefanklug I finally managed to solve the problem. The thing was that I didn't understand that the Wayland Terminal Window referes to a HDMI display connected to the DSI port through a CSI to HDMI bridge. Once that the system booted I clicked in the terminal icon and type there pylon and it worked. Thank u for ur reply :)
