### ISSUE TITLE
Sources on codeaurora.org not available anymore and in the future - step 2 not working

### ISSUE THREAD

**Issue by Notwista** [basler/meta-basler-imx8#9]
See https://bye.codeaurora.org/

Solution found for Kirkstone release and step 2:
`repo init -u https://github.com/nxp-imx/imx-manifest -b imx-linux-kirkstone -m imx-5.15.71-2.2.0.xml
`

**Comment by toklinke** [comment]
Hi @Notwista, yes, the README was outdated. Now the correct URL is included.
